### PR TITLE
Change website UI

### LINKED ISSUE #287: Website UI changes
- [x] Home should be added to Navigation bar
- [x] Navigation bar - Change from "About" to "About Us"
- [x] Home Page add logo from here: https://drive.google.com/drive/folders/1d0h0AUNRk-SPDAxw_GPQcf_aTxM061ZX
Screen Shot 2022-07-28 at 10 19 31

- [x] 1) Split up the home page paragraph into two paragraphs in the same box AND 2) Capitalize the "L" in Lanka, AND 3) make the text bold black:
Sri Lanka is going through an unprecedented economic crisis. It has left the country facing a severe shortage of life-saving medicines and medical supplies.

The Elixir platform facilitates matches donations with the most urgent and provides transparency.
Screen Shot 2022-07-28 at 10 19 31

- [x] Make the text in these paragraphs bold black:
Screen Shot 2022-07-28 at 10 26 07

- [x] Improve the look and text of the below message:
Message: No pledged packages found. Check the "Goal Pending" tab to find aid packages you can pledge towards. 

Screen Shot 2022-07-28 at 10 11 55

- [x] Remove Privacy, Cookies, Terms at the bottom of the Home Page (for all pages)
Screen Shot 2022-07-28 at 10 21 02

- [x] About Us>Accountability and transparency section, change a typo in the highlighted text shown in the image to read:
 Please contact us at elixir@redcross.lk should you have any questions or feedback for us.

Screen Shot 2022-07-28 at 10 37 17

- [x] Change the position of headers once you click the navigation bar/menu pages all to the LEFT e.g. About Us (left), How to Donate (center), Newsroom (left), Medical Supplies (center). Make sure header is same size font (same as About Us). 
Screen Shot 2022-07-28 at 09 59 00
Screen Shot 2022-07-28 at 09 59 07

- [x] Email address on all pages needs to be: elixir@redcross.lk. Check the following images:

**How to Donate Page email address in TWO places.**
Screen Shot 2022-07-28 at 10 43 15

**Medical Suppliers page:**
Screen Shot 2022-07-28 at 10 44 15

- [x] On the inside page of Medical Suppliers, change the heading to Hospitals and Suppliers and align LEFT
Screen Shot 2022-07-28 at 10 07 24

- [x] Top paragraph text to be at least 14 point on ALL pages. 
Screen Shot 2022-07-28 at 10 09 28

### PR DESCRIPTION
**Pull request by RandilaP**
## Purpose

The purpose of this PR is to fix #287 

## Goals
- Add home to nav bar
- Change about to about us in nav bar
- Edit homepage content
- Change emails in every page
- Change Doctors to hospitals
- 

### Screenshots

image
image

image

### CODE REVIEW

**Comment by RandilaP** [comment]
How can I make this a Draft one..

**Comment by anjula-sack** [comment]
> How can I make this a Draft one..

Is this PR ready for review? @RandilaP

**Comment by RandilaP** [comment]
@anjula-sack Still not I guess.. There are several minor details to add

**Comment by anjula-sack** [comment]
Screenshot 2022-07-29 at 8 48 33 AM
header content seems to be out of the container. Refer to the other pages headers to see the difference

**Review by jayasanka-sack — APPROVED** [review]
Thanks @RandilaP !

**Pull request merged**
