### PR TITLE
Navbar should close when a navlink is closed

### LINKED ISSUE #439: Mobile navbar is not closing when the user click somewhere outside the navbar
**Is your feature request related to a problem? Please describe.**
- Mobile navbar is not closing when the user click somewhere outside the navbar

**Describe the solution you'd like**
- Mobile navbar should close when the user click somewhere outside the navbar

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #439 

## Goals

- Navbar should behave correctly on mobile view
## Approach

- Add the navbar toggler click event for the navbar links

### CODE REVIEW

**Comment by dinuka-rp** [comment]
@anjula-sack I think u overrode ur code and it doesn't work as expected now.
I tested on both web responsive view & mobile. Can u pls check?

**Comment by anjula-sack** [comment]
> @anjula-sack I think u overrode ur code and it doesn't work as expected now.
> 
> I tested on both web responsive view & mobile. Can u pls check?

Once you clicked on a nav item it is getting closed. Event listener is not necessary.

**Comment by dinuka-rp** [comment]
@anjula-sack oh ok, got it.
I thought that u implemented closing the navbar, when a user touches outside the nav menu

**Review by dinuka-rp — APPROVED** [review]
Thanks @anjula-sack !

**Pull request merged**
