### PR TITLE
Add delete aid package button for draft packages

### LINKED ISSUE #210: Should be able to delete draft and any status packages before publishing.
- [ ] Should be able to delete draft and any status packages before publishing.

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #210 

## Goals

- Giving the ability to delete aid packages that are in the draft state

## Approach

- Created the delete package modal
- Added the delete aid package API 

### Screenshots

Screenshot 2022-07-22 at 3 28 02 PM
Screenshot 2022-07-22 at 3 30 19 PM

### CODE REVIEW

**Comment by anjula-sack** [comment]
@nshamit I added the delete button like above and only visible if the package is in ` draft ` state. But I'm missing the delete package API.

**Comment by nshamit** [comment]
@AmilaJ @anupama-pathirage can you help with this?

**Comment by anjula-sack** [comment]
> @AmilaJ @anupama-pathirage can you help with this?

I checked the backend, seems like the API is not there.

**Comment by jayasanka-sack** [comment]
This PR needs to be merged:

https://github.com/LSFLK/MedicinesforLK-DonorAPI/pull/19

**Comment by jayasanka-sack** [comment]
Can be merged after https://github.com/LSFLK/MedicinesforLK-AdminAPI/pull/51

**Review by jayasanka-sack — APPROVED** [review]
Thanks @anjula-sack !

**Pull request merged**
