### PR TITLE
Social Media Optimization 📱

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Adding social medial related `meta` tags.

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Review by dinuka-rp — CHANGES_REQUESTED** [review]
Thanks for the PR!

Can u link the Elixr logo that in the website for og:image? https://elixir.redcross.lk/

You can use this image
Elixir Logo

**Comment by dinuka-rp** [comment]
Maybe it's a good idea to reduce the scale of this image 😂

**Comment by dinuka-rp** [comment]
Maybe it's a good idea to reduce the scale of this image 😂

**Comment by sanjaiyan-dev** [comment]
> Maybe it's a good idea to reduce the scale of this image 😂

Done 💪🏽

**Review by dinuka-rp — APPROVED** [review]
Thanks @sanjaiyan-dev !

**Pull request merged**
