### PR TITLE
Feature/timestamp local - use UNIX epoch time in the admin portal

### LINKED ISSUE #184: Check time stamps and make sure they are in SL time.

### PR DESCRIPTION
**Pull request by dinuka-rp**
## Purpose

The purpose of this PR is to fix #184

## Goals
Use Unix epoch in all places, to get the time required to be displayed relative to local time.

### CODE REVIEW

**Comment by dinuka-rp** [comment]
Don't merge this PR until the backend sends the dateTime as a UNIX epoch (10-digit number) in all required places.

**Comment by anjula-sack** [comment]
> Don't merge this PR until the backend sends the dateTime as a UNIX epoch (10-digit number) in all required places.

The build is failing can you check? @dinuka-rp

**Comment by dinuka-rp** [comment]
@anjula-sack yep, it's a type issue. Gotta fix that and push.

The problem is that the backend seems to require the current type schema. I'm unsure what to do.

**Comment by dinuka-rp** [comment]
TODO: dateTime may have to be [*1000 to get the correct datetime](https://stackoverflow.com/a/847196/11005638)
This may be needed for sorting comments based on date time.

- [ ] Check if Unix epoch can be directly used to find the difference in times - for the sorting function

**Comment by dinuka-rp** [comment]
Complete rest of the changes, test and merge this once the backend changes requested in https://github.com/LSFLK/MedicinesforLK/issues/184#issuecomment-1210634750 are completed

**Comment by anjula-sack** [comment]
@dinuka-rp can you fix the conflicts? Is this ready to merge now?

**Comment by dinuka-rp** [comment]
@anjula-sack I fixed the conflict. Last time, the API wasn't working as expected to test this.
I saw that Manu had mentioned that I can make the changes now since the backend supports UNIX timestamps.

I'll test this locally & ping u here to get it reviewed.

**Comment by dinuka-rp** [comment]
@anjula-sack I tested this. Getting & displaying the datetime in local format works as expected from the frontend & can be merged.

Update seems to fail as mentioned in #428 
That needs to be fixed from the backend.

**Comment by dinuka-rp** [comment]
@anjula-sack can u pls review & merge this?
I tested it. It's working as expected

**Review by anjula-sack — APPROVED** [review]

**Pull request merged**
