### PR TITLE
Code splitting for improved performance 🚀 

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Improving the initial loading speed by code splitting the route components and making subsequent navigation faster by [prefetching](https://web.dev/link-prefetch/).

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Review by dinuka-rp — CHANGES_REQUESTED** [review]
Thanks for the PR @sanjaiyan-dev !
Can u use a formatter like Prettier to format the files that u edited? The builds are failing because of formatting issues.

**Comment by sanjaiyan-dev** [comment]
> Thanks for the PR @sanjaiyan-dev ! Can u use a formatter like Prettier to format the files that u edited? The builds are failing because of formatting issues.

Done 🤝

**Comment by sanjaiyan-dev** [comment]
Benchmarks -:

Before update
Screenshot_2022-09-04-14-30-18-576_com android chrome

After update
Screenshot_2022-09-04-14-31-12-749_com android chrome

🚀🚀🚀

**Review by dinuka-rp — APPROVED** [review]
Thanks a lot for all the performance updates @sanjaiyan-dev !

**Pull request merged**
