### PR TITLE
Assign donor portal API endpoints to env variables

### PR DESCRIPTION
**Pull request by dinuka-rp**
## Purpose
Configure API endpoint URLs for multiple environments

## Approach
Use ENV variables to load API endpoint URLs.

### CODE REVIEW

**Comment by dinuka-rp** [comment]
@manuranga pls check if the required ENV variables have been used here

**Comment by dinuka-rp** [comment]
I've set the env variables to the Admin & Donor APIs for the production & development branches on Vercel as well.

**Comment by dinuka-rp** [comment]
Used the same name ('rouge') as in the Admin portal Domain configuration on Vercel
image

**Review by anjula-sack — APPROVED** [review]

**Comment by dinuka-rp** [comment]
image

**Review by manuranga — APPROVED** [review]

**Pull request merged**
