### PR TITLE
Update the max pledge calculation in the update pledge

### LINKED ISSUE #265: 594% pledge in aid packages view
- [ ] 594% pledge in aid packages view. Should only be able to pledge 0-100% of the aid package value / need. 

Screen Shot 2022-07-26 at 19 06 46

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #265 

## Goals

- Prevent users from pledging more than the pledge

## Approach

- Update the max pledge calculation in the update pledge

### Screenshots

Screenshot 2022-07-28 at 1 00 14 PM

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
I don't think the issue is with the frontend. I think the current calculation is correct. What might have happened is some has updated values from the backend.

 @Gravewalker666 could you please review this?

**Comment by Gravewalker666** [comment]
Yeah the current max value expression is correct, it doesn't need to be changed

**Comment by anjula-sack** [comment]
> Yeah the current max value expression is correct, it doesn't need to be changed

Why do we need to add `pledge.amount`?  With that, it shows more than the pledge amount.

Refer to the screenshot it shows 8000 which is correct (11900 - 3900). But adding `pledge.amount` shows 10700 (8000+2700) as the max pledge. 

Yeah, we need backend validation but for this version, backend validation was not considered.

cc: @jayasanka-sack

**Comment by Gravewalker666** [comment]
@anjula-sack That's because you're updating the amount, not adding a new pledge value. 
That 3900 at the top already got the amount that this user has already pledged. 
They've pledged 2700 already, Now imagine they wanna update their pledge amount to max out the entire goal, so the value they should pledge at that point is 2700 + 8000, which adds unto 10700. But maximum value the expression on this PR allows is 8000. :)

**Comment by Gravewalker666** [comment]
On in better simple terms, you've already pledged 2700 you can increase it up to 10700.

**Comment by anjula-sack** [comment]
> 

Got it. I got confused between adding a new value and updating. Hope users won't get confused.

**Pull request closed without merging**
