### PR TITLE
Fix package title overlapping issue in mobile view

### LINKED ISSUE #503: Mobile responsiveness: package titles are cropped/ overlapping
- [ ] Mobile responsiveness: package titles are cropped/ overlapping

From Anjula:
From Anjula

From Sherazad, iphone:
From iphone

### PR DESCRIPTION
**Pull request by kanushka**
## Purpose

The purpose of this PR is to fix #503
Fix package title overlapping issue in mobile view.

### Screenshots

image

### CODE REVIEW

**Comment by anjula-sack** [comment]
can't we show the full title there? @kanushka

**Comment by kanushka** [comment]
We could 
But longer title will messed up the card height.

We can add two line or make title font size smaller

**Comment by anjula-sack** [comment]
> 

we can go with making it smaller and the breaking into two lines @kanushka

**Comment by kanushka** [comment]
Update Package title with 2 lines. 

image

**Review by anjula-sack — APPROVED** [review]
Thank you! @kanushka

**Pull request merged**
